// Copyright Epic Games, Inc. All Rights Reserved.

#include "LogiclessButtons.h"

#include "Kismet2/KismetEditorUtilities.h"
#include "Object/ButtonCommand.h"

#define LOCTEXT_NAMESPACE "FLogiclessButtonsModule"

void FLogiclessButtonsModule::StartupModule()
{
	// This code will execute after your module is loaded into memory; the exact timing is specified in the .uplugin file per-module

	FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UButtonCommand::StaticClass(), "OnCommandConstructedFromList");
	FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UButtonCommand::StaticClass(), "OnButtonClicked");
	FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, UButtonCommand::StaticClass(), "OnButtonReleased");
}

void FLogiclessButtonsModule::ShutdownModule()
{
	// This function may be called during shutdown to clean up your module.  For modules that support dynamic reloading,
	// we call this function before unloading the module.
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FLogiclessButtonsModule, LogiclessButtons)
